"""add project_id to comments

Revision ID: 803329a9076d
Revises: 72f2592f4f7d
Create Date: 2026-02-26 05:19:25.188673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803329a9076d'
down_revision: Union[str, None] = '72f2592f4f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'comments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'project_id')
    # ### end Alembic commands ###
