"""create audit_logs table and some edit in attachmmnts 

Revision ID: b50e9b9f0a9d
Revises: d96a91ae8041
Create Date: 2026-02-11 11:43:23.155880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50e9b9f0a9d'
down_revision: Union[str, None] = 'd96a91ae8041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tickets')
    op.drop_table('notifications')
    op.alter_column('attachments', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('attachments_card_id_fkey', 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'cards', ['card_id'], ['id'])
    op.drop_column('attachments', 'task_id')
    op.drop_column('attachments', 'file_type')
    op.drop_constraint('comments_task_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_card_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'cards', ['card_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'tasks', ['task_id'], ['id'])
    op.drop_column('lists', 'updated_at')
    op.drop_column('lists', 'created_at')
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.add_column('time_entries', sa.Column('task_id', sa.UUID(), nullable=True))
    op.drop_constraint('time_entries_card_id_fkey', 'time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_entries', 'tasks', ['task_id'], ['id'])
    op.drop_column('time_entries', 'card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('card_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.create_foreign_key('time_entries_card_id_fkey', 'time_entries', 'cards', ['card_id'], ['id'])
    op.drop_column('time_entries', 'task_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_project_id_fkey', 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('lists', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('lists', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_card_id_fkey', 'comments', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comments_task_id_fkey', 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('attachments', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_card_id_fkey', 'attachments', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attachments', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'resolved', 'closed', name='ticketstatus'), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'critical', name='ticketpriority'), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='tickets_assignee_id_fkey'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='tickets_requester_id_fkey'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='tickets_workspace_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tickets_pkey')
    )
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
