"""fix workspace models

Revision ID: c0f6c26cf270
Revises: 
Create Date: 2026-02-11 16:26:38.398476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0f6c26cf270'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.alter_column('attachments', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('lists', 'created_at')
    op.drop_column('lists', 'updated_at')
    op.alter_column('time_entries', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('time_entries', 'card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('card_id', sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column('time_entries', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('lists', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('lists', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('attachments', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('object_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    # ### end Alembic commands ###
